# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Forum.create!(title: "General")
Forum.create!(title: "Washington Capitals", team_abbrev: "WAS")
Forum.create!(title: "Vancouver Canucks", team_abbrev: "VAN")
Forum.create!(title: "Toronto Maple Leafs", team_abbrev: "TOR")
Forum.create!(title: "New York Rangers", team_abbrev: "NYR")
Forum.create!(title: "Minnesota Wild", team_abbrev: "MIN")
Forum.create!(title: "San Jose Sharks", team_abbrev: "SJS")
Forum.create!(title: "Ottawa Senators", team_abbrev: "OTT")
Forum.create!(title: "Detroit Red Wings", team_abbrev: "DET")
Forum.create!(title: "Columbus Blue Jackets", team_abbrev: "CBJ")
Forum.create!(title: "New York Islanders", team_abbrev: "NYI")
Forum.create!(title: "Winnipeg Jets", team_abbrev: "WPG")
Forum.create!(title: "Philadelphia Flyers", team_abbrev: "PHI")
Forum.create!(title: "Dallas Stars", team_abbrev: "DAL")
Forum.create!(title: "Phoenix Coyotes", team_abbrev: "PHO")
Forum.create!(title: "Buffalo Sabres", team_abbrev: "BUF")
Forum.create!(title: "New Jersey Devils", team_abbrev: "NJD")
Forum.create!(title: "Edmonton Oilers", team_abbrev: "EDM")
Forum.create!(title: "Carolina Hurricanes", team_abbrev: "CAR")
Forum.create!(title: "Calgary Flames", team_abbrev: "CGY")
Forum.create!(title: "Tampa Bay Lightning", team_abbrev: "TAM")
Forum.create!(title: "Nashville Predators", team_abbrev: "NSH")
Forum.create!(title: "Colorado Avalanche", team_abbrev: "COL")
Forum.create!(title: "Florida Panthers", team_abbrev: "FLA")
Forum.create!(title: "Chicago Blackhawks", team_abbrev: "CHI")
Forum.create!(title: "Anaheim Ducks", team_abbrev: "ANA")
Forum.create!(title: "Pittsburgh Penguins", team_abbrev: "PIT")
Forum.create!(title: "St. Louis Blues", team_abbrev: "STL")
Forum.create!(title: "Boston Bruins", team_abbrev: "BOS")
Forum.create!(title: "Montreal Canadiens", team_abbrev: "MON")
Forum.create!(title: "Los Angeles Kings", team_abbrev: "LOS")